app = "sanyuth"
primary_region = "bom"

[env]
PORT = "8000"
PYTHONPATH = "/app"

[experimental]
auto_rollback = true

  [experimental.attached]
  secrets = { }

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8_000
min_machines_running = 1
processes = [ "app" ]

  [[http_service.checks]]
  grace_period = "20s"
  interval = "30s"
  method = "GET"
  path = "/api/health"
  timeout = "10s"

[[statics]]
guest_path = "/app/static"
tigris_bucket = ""
url_prefix = "/static/"
